name: ğŸ› ï¸CloudFormation Deployment

on:
  push:
    branches: [master, main]
  workflow_dispatch:

env:
  REGION: 'us-east-1'

jobs:
  cloudformation:
    name: ğŸ› ï¸ Cloudformation
    runs-on: ubuntu-latest

    steps:
    - name: Get code # get code from repository to server
      uses: actions/checkout@v4 # action to use - https://github.com/actions/checkout

    - name: ğŸ”‘AWS credentials configuration
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.REGION }}

    - name: ğŸ—ï¸ Setup cloudformation deployment
      run: |
        aws cloudformation deploy \
        --stack-name $STACK_NAME_VPC \
        --template-file network.yml \
        --parameter-overrides file://network-parameters.json \
        --capabilities CAPABILITY_NAMED_IAM \
        --region $REGION
